apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgCbl8ABTpBrIZxE9qqus30IuEvUd8p1wMG/5Vmlj7KLFhvNitu8u40t+mRd3CN/mUs41IwUq6tzxKjhuQ9kHIr+80Isj5jG5icPqXZj2okJRng/cIjiXAqLmr7zRXnqWy9iMatW50Gu4yaheyn1r1Bp12R7tswh59eWbC9HziOuU15U7CFcGEn8yRf6p8pIi8wBmRhwACmDPWWNhLLrtdef4TbvYEYCWj/MuXGWguki2LD2GMNgJx0FUKmSzFf/dOMt5ruNCQ4Ao8MZkyAW9Hp5aszIEF08YlaA3/lw10ARL9ZPSQ8poZgcZdoGR8aaSaItiTFI0WICjl1XSpy3nSE4FHCBDjNjylnwOZVKkKzL2d03H50J/upl84NLQaMm1x4MV5zRkTnmDzaCWe3e2EOap3hWgaKkRWA1PwMKsyHutskyaAHdCnq5v03AF9ErChzOIgmOLMO2ia3HrOhnFW3Kh/+eYXUtAQEWmRAzqSrqA5VE4B6FidQjbJSUaSencLj13/0nZJcN8YeBmmCmmHLD3mVINHGr3DZrpYXJMw+R0Ene8knoZm4TATjjWgxlrI5eErn2VsTZrpRTM84n8nS8x7/B9wB4X2Jx6xb9+HKxBBsK5Yiek+M9r7WHsdwjfj6J1TCjyPH+nNVDPBhjhaCoHZaRk5D/QII845Z3yGt2gXr5sEaRMGwhIkYFEQ3Lcq5MDwNeNSnTiDQ=
    username: AgArLQ5Z3vg0q4C/0y6rnachTb5423WEd/fottNfoSOnA20hAVjAEZhFZxyvpAQnHn3G7M6D7AgdCJlR/RGmatN6SDMQWy6GnstoGbHsJ5PYrin9i/+SpF/JQXDL2NzjSOtivDVJxJBLX2euJuGyT4CIOS9PkmomBUkRGiSEGIsUOFkQE5BzT2J5NxeL2zjCez5rmAbfS48ddCrNue2o2y2zc1fQpHJq3Bmn5SX5+tnRHYmOkERutbQnguiEjR1rUXgsCNgnwoGayMrUJRK2sWyH8xQFiFkDoARBzfdh481XDQ1v+t6pASfNjiVkBqtyCEyDXqbEadKZJxo9YpnhcQbT3aCZXUHeqys2uqVLi80AC5XMU+SOtoqbff04YtGvQt1kUKgPXI3Z58jmfDzHTJ5lXzka+IuV29UZ9xvLCy/wQxfJ+gjNGLpbz6rA7yktPEpw8SlRNEzMCaTlCW3C5N3qqibdeQc1QlIk40pmnP61h5UpuZFyEfa4vCJ0h8eALwDU2ga/qHbqh9SK6lM6kG4iGqW9bY4hSc3IyIqHqCjsxFE8XqQR+7FtBcvg0BR5E5Pt3WBBlMg/7V017QUhWMuYFiUZH59KdIsETwox7xQ+/9FNRmbfqjDI3cVkuuM9T5FZAXHtVtAFfrriTMaSYhBz+gVRB/zEsfdEl8rQaTIaUdqq2C0pBoHgjkJSMp8KCNDSG9+ZuZaUR2s=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

